{% set name = "javaobj-py3" %}
{% set version = "0.4.0.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "18c44cfaa214813784a823432b4ab9829c9626b2b00072011627b4008b0067cd" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - javaobj

about:
  home: https://github.com/tcalmant/python-javaobj
  license: Apache Software
  license_file: LICENSE
  license_family: APACHE
  summary: Module for serializing and de-serializing Java objects.
  description: |
    provides functions for reading and writing (writing is WIP currently) Java objects serialized or will be
    deserialized by ``ObjectOutputStream``. This form of object representation is a standard data interchange
    format in Java world.

extra:
  recipe-maintainers:
    - msarahan
