{% set name = "javaobj-py3" %}
{% set version = "0.3.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': 'a57469e4f0d0eeba7482ad9839595db6e99ca4ac6630a4c8064dda75a2182549'

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - javaobj

about:
  home: https://github.com/tcalmant/python-javaobj
  license: Apache Software
  license_family: APACHE
  summary: Module for serializing and de-serializing Java objects.
  description: |
    provides functions for reading and writing (writing is WIP currently) Java objects serialized or will be
    deserialized by ``ObjectOutputStream``. This form of object representation is a standard data interchange
    format in Java world.

extra:
  recipe-maintainers:
    - msarahan
